plugins {
    id 'java'
}

group 'org.springframework'
version '5.2.10.BUILD-SNAPSHOT'
apply plugin: 'war'
repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

dependencies {
    // JSR 303 API
    compile group: 'javax.inject', name: 'javax.inject', version: '1'

    compile group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
    compile group: 'javax.servlet.jsp', name: 'javax.servlet.jsp-api', version: '2.3.3'
    // yaml文件解析工具类
    compile group: 'org.yaml', name: 'snakeyaml', version: '1.27'

    // implementation group: 'org.projectlombok', name: 'lombok', version: '1.18.18'
    // annotationProcessor("org.projectlombok:lombok:1.18.18")

    compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.21'
    compile("com.alibaba:druid:1.1.8")
    compile(project(":spring-core")) // 代表本项目的
    compile(project(":spring-beans"))
    compile(project(":spring-aop"))
    compile(project(":spring-context"))
    compile(project(":spring-jdbc"))
    compile(project(":spring-web"))
    compile(project(":spring-webmvc"))
    compile(project(":spring-jdbc"))
    compile(project(":spring-tx"))
    compile(project(":spring-test"))
    optional("org.aspectj:aspectjweaver")
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testImplementation 'org.hamcrest:hamcrest-core:2.1'
}
