jdbc.driver=com.mysql.cj.jdbc.Driver
# jdbc.url=jdbc:mysql://192.168.159.135:3306/cms?characterEncoding=utf-8
jdbc.url=jdbc:mysql://192.168.159.135:3306/heima?serverTimezone=GMT%2B8
jdbc.username=root
jdbc.password=admin